[package]
name    = "gstreamer"
description = "Idiomatic bindings for GStreamer"
homepage = "https://github.com/arturoc/gstreamer1.0-rs"
repository = "https://github.com/arturoc/gstreamer1.0-rs"
readme = "README.md"
license = "MIT"
version = "0.1.6"
authors = [ "Arturo Castro <mail@arturocastro.net>" ]
build = "build.rs"

[lib]
name = "gst"
path = "src/lib.rs"


